# Generated by Django 5.0 on 2023-12-28 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ("airplane_type", "rows", "seats_in_row")},
        ),
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ("last_name",)},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ("-departure_time", "-arrival_time")},
        ),
    ]
