# Generated by Django 5.0 on 2024-01-01 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airport",
            options={},
        ),
    ]
