# Generated by Django 5.0 on 2024-01-01 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_alter_airport_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ("name",)},
        ),
    ]
