# Generated by Django 5.0 on 2024-11-30 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_msg', '0002_chatsupport_author_created_chatsupport_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsupport',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsupport',
            name='user_list',
            field=models.ManyToManyField(related_name='participated_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsupport',
            name='author_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
